### ISSUE TITLE
More than 2 modules won't show up

### ISSUE THREAD

**Issue by Cicin2837512** [vivien/i3blocks#492]
Here is a simple i3blocks configuration
```toml
[memory]
command=free -m | grep Mem | awk '{printf("MEM %d%%\n", $3/$2 * 100)}'
interval=10

[wifi]
command=nmcli dev wifi list | grep '^\*' | awk '{printf("WIFI %s %s\n", $3, $9)}'
interval=10

[cpu]
command=mpstat | grep all | awk '{printf("CPU %d%\n", $4)}' 
interval=10
```
No matter what I do, no more than 2 of these modules will show up. If I change the order, it's always the first 2 only. It does the same thing when I run it in the terminal, and the problem is not with the commands or anything. It's just the order that decides which will show up. I'm probably missing some stupid little thing, but I've been searching online and I genuinely have no idea why it won't just work because it seems like this should work without any problems.
